#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfReestr
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Bazis")]
	public partial class StarahReestrDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertStrahFile(StrahFile instance);
    partial void UpdateStrahFile(StrahFile instance);
    partial void DeleteStrahFile(StrahFile instance);
    partial void Inserts_StrahComp(s_StrahComp instance);
    partial void Updates_StrahComp(s_StrahComp instance);
    partial void Deletes_StrahComp(s_StrahComp instance);
    partial void Inserts_Oblast(s_Oblast instance);
    partial void Updates_Oblast(s_Oblast instance);
    partial void Deletes_Oblast(s_Oblast instance);
    partial void InsertStrahSpr(StrahSpr instance);
    partial void UpdateStrahSpr(StrahSpr instance);
    partial void DeleteStrahSpr(StrahSpr instance);
    partial void InsertStrahReestr(StrahReestr instance);
    partial void UpdateStrahReestr(StrahReestr instance);
    partial void DeleteStrahReestr(StrahReestr instance);
    #endregion
		
		public StarahReestrDataContext() : 
				base(global::wpfReestr.Properties.Settings.Default.BazisConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public StarahReestrDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StarahReestrDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StarahReestrDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StarahReestrDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StrahFile> StrahFile
		{
			get
			{
				return this.GetTable<StrahFile>();
			}
		}
		
		public System.Data.Linq.Table<s_StrahComp> s_StrahComp
		{
			get
			{
				return this.GetTable<s_StrahComp>();
			}
		}
		
		public System.Data.Linq.Table<s_Oblast> s_Oblast
		{
			get
			{
				return this.GetTable<s_Oblast>();
			}
		}
		
		public System.Data.Linq.Table<StrahSpr> StrahSpr
		{
			get
			{
				return this.GetTable<StrahSpr>();
			}
		}
		
		public System.Data.Linq.Table<StrahReestr> StrahReestr
		{
			get
			{
				return this.GetTable<StrahReestr>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StrahFile")]
	public partial class StrahFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cod;
		
		private System.Nullable<System.DateTime> _DateN;
		
		private System.Nullable<System.DateTime> _DateK;
		
		private System.Nullable<int> _Korekt;
		
		private System.Nullable<byte> _StrahComp;
		
		private System.Nullable<byte> _Tip;
		
		private System.Nullable<int> _YEAR;
		
		private System.Nullable<int> _MONTH;
		
		private System.Nullable<int> _NSCHET;
		
		private System.Nullable<System.DateTime> _DSCHET;
		
		private System.Nullable<decimal> _SUMMAV;
		
		private System.Nullable<byte> _pPaket;
		
		private System.Nullable<byte> _pHide;
		
		private System.Nullable<System.DateTime> _pDate;
		
		private System.Nullable<System.DateTime> _pUpDate;
		
		private System.Nullable<int> _pParent;
		
		private System.Nullable<byte> _VMP;
		
		private EntitySet<StrahReestr> _StrahReestr;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodChanging(int value);
    partial void OnCodChanged();
    partial void OnDateNChanging(System.Nullable<System.DateTime> value);
    partial void OnDateNChanged();
    partial void OnDateKChanging(System.Nullable<System.DateTime> value);
    partial void OnDateKChanged();
    partial void OnKorektChanging(System.Nullable<int> value);
    partial void OnKorektChanged();
    partial void OnStrahCompChanging(System.Nullable<byte> value);
    partial void OnStrahCompChanged();
    partial void OnTipChanging(System.Nullable<byte> value);
    partial void OnTipChanged();
    partial void OnYEARChanging(System.Nullable<int> value);
    partial void OnYEARChanged();
    partial void OnMONTHChanging(System.Nullable<int> value);
    partial void OnMONTHChanged();
    partial void OnNSCHETChanging(System.Nullable<int> value);
    partial void OnNSCHETChanged();
    partial void OnDSCHETChanging(System.Nullable<System.DateTime> value);
    partial void OnDSCHETChanged();
    partial void OnSUMMAVChanging(System.Nullable<decimal> value);
    partial void OnSUMMAVChanged();
    partial void OnpPaketChanging(System.Nullable<byte> value);
    partial void OnpPaketChanged();
    partial void OnpHideChanging(System.Nullable<byte> value);
    partial void OnpHideChanged();
    partial void OnpDateChanging(System.Nullable<System.DateTime> value);
    partial void OnpDateChanged();
    partial void OnpUpDateChanging(System.Nullable<System.DateTime> value);
    partial void OnpUpDateChanged();
    partial void OnpParentChanging(System.Nullable<int> value);
    partial void OnpParentChanged();
    partial void OnVMPChanging(System.Nullable<byte> value);
    partial void OnVMPChanged();
    #endregion
		
		public StrahFile()
		{
			this._StrahReestr = new EntitySet<StrahReestr>(new Action<StrahReestr>(this.attach_StrahReestr), new Action<StrahReestr>(this.detach_StrahReestr));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Cod
		{
			get
			{
				return this._Cod;
			}
			set
			{
				if ((this._Cod != value))
				{
					this.OnCodChanging(value);
					this.SendPropertyChanging();
					this._Cod = value;
					this.SendPropertyChanged("Cod");
					this.OnCodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateN", DbType="Date")]
		public System.Nullable<System.DateTime> DateN
		{
			get
			{
				return this._DateN;
			}
			set
			{
				if ((this._DateN != value))
				{
					this.OnDateNChanging(value);
					this.SendPropertyChanging();
					this._DateN = value;
					this.SendPropertyChanged("DateN");
					this.OnDateNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateK", DbType="Date")]
		public System.Nullable<System.DateTime> DateK
		{
			get
			{
				return this._DateK;
			}
			set
			{
				if ((this._DateK != value))
				{
					this.OnDateKChanging(value);
					this.SendPropertyChanging();
					this._DateK = value;
					this.SendPropertyChanged("DateK");
					this.OnDateKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Korekt", DbType="Int")]
		public System.Nullable<int> Korekt
		{
			get
			{
				return this._Korekt;
			}
			set
			{
				if ((this._Korekt != value))
				{
					this.OnKorektChanging(value);
					this.SendPropertyChanging();
					this._Korekt = value;
					this.SendPropertyChanged("Korekt");
					this.OnKorektChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StrahComp", DbType="TinyInt")]
		public System.Nullable<byte> StrahComp
		{
			get
			{
				return this._StrahComp;
			}
			set
			{
				if ((this._StrahComp != value))
				{
					this.OnStrahCompChanging(value);
					this.SendPropertyChanging();
					this._StrahComp = value;
					this.SendPropertyChanged("StrahComp");
					this.OnStrahCompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tip", DbType="TinyInt")]
		public System.Nullable<byte> Tip
		{
			get
			{
				return this._Tip;
			}
			set
			{
				if ((this._Tip != value))
				{
					this.OnTipChanging(value);
					this.SendPropertyChanging();
					this._Tip = value;
					this.SendPropertyChanged("Tip");
					this.OnTipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="Int")]
		public System.Nullable<int> YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this.OnYEARChanging(value);
					this.SendPropertyChanging();
					this._YEAR = value;
					this.SendPropertyChanged("YEAR");
					this.OnYEARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTH", DbType="Int")]
		public System.Nullable<int> MONTH
		{
			get
			{
				return this._MONTH;
			}
			set
			{
				if ((this._MONTH != value))
				{
					this.OnMONTHChanging(value);
					this.SendPropertyChanging();
					this._MONTH = value;
					this.SendPropertyChanged("MONTH");
					this.OnMONTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NSCHET", DbType="Int")]
		public System.Nullable<int> NSCHET
		{
			get
			{
				return this._NSCHET;
			}
			set
			{
				if ((this._NSCHET != value))
				{
					this.OnNSCHETChanging(value);
					this.SendPropertyChanging();
					this._NSCHET = value;
					this.SendPropertyChanged("NSCHET");
					this.OnNSCHETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCHET", DbType="Date")]
		public System.Nullable<System.DateTime> DSCHET
		{
			get
			{
				return this._DSCHET;
			}
			set
			{
				if ((this._DSCHET != value))
				{
					this.OnDSCHETChanging(value);
					this.SendPropertyChanging();
					this._DSCHET = value;
					this.SendPropertyChanged("DSCHET");
					this.OnDSCHETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMMAV", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> SUMMAV
		{
			get
			{
				return this._SUMMAV;
			}
			set
			{
				if ((this._SUMMAV != value))
				{
					this.OnSUMMAVChanging(value);
					this.SendPropertyChanging();
					this._SUMMAV = value;
					this.SendPropertyChanged("SUMMAV");
					this.OnSUMMAVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pPaket", DbType="TinyInt")]
		public System.Nullable<byte> pPaket
		{
			get
			{
				return this._pPaket;
			}
			set
			{
				if ((this._pPaket != value))
				{
					this.OnpPaketChanging(value);
					this.SendPropertyChanging();
					this._pPaket = value;
					this.SendPropertyChanged("pPaket");
					this.OnpPaketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pHide", DbType="TinyInt")]
		public System.Nullable<byte> pHide
		{
			get
			{
				return this._pHide;
			}
			set
			{
				if ((this._pHide != value))
				{
					this.OnpHideChanging(value);
					this.SendPropertyChanging();
					this._pHide = value;
					this.SendPropertyChanged("pHide");
					this.OnpHideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> pDate
		{
			get
			{
				return this._pDate;
			}
			set
			{
				if ((this._pDate != value))
				{
					this.OnpDateChanging(value);
					this.SendPropertyChanging();
					this._pDate = value;
					this.SendPropertyChanged("pDate");
					this.OnpDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pUpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> pUpDate
		{
			get
			{
				return this._pUpDate;
			}
			set
			{
				if ((this._pUpDate != value))
				{
					this.OnpUpDateChanging(value);
					this.SendPropertyChanging();
					this._pUpDate = value;
					this.SendPropertyChanged("pUpDate");
					this.OnpUpDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pParent", DbType="Int")]
		public System.Nullable<int> pParent
		{
			get
			{
				return this._pParent;
			}
			set
			{
				if ((this._pParent != value))
				{
					this.OnpParentChanging(value);
					this.SendPropertyChanging();
					this._pParent = value;
					this.SendPropertyChanged("pParent");
					this.OnpParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VMP", DbType="TinyInt")]
		public System.Nullable<byte> VMP
		{
			get
			{
				return this._VMP;
			}
			set
			{
				if ((this._VMP != value))
				{
					this.OnVMPChanging(value);
					this.SendPropertyChanging();
					this._VMP = value;
					this.SendPropertyChanged("VMP");
					this.OnVMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StrahFile_StrahReestr", Storage="_StrahReestr", ThisKey="Cod", OtherKey="CodFile")]
		public EntitySet<StrahReestr> StrahReestr
		{
			get
			{
				return this._StrahReestr;
			}
			set
			{
				this._StrahReestr.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StrahReestr(StrahReestr entity)
		{
			this.SendPropertyChanging();
			entity.StrahFile = this;
		}
		
		private void detach_StrahReestr(StrahReestr entity)
		{
			this.SendPropertyChanging();
			entity.StrahFile = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.s_StrahComp")]
	public partial class s_StrahComp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KOD;
		
		private string _TKOD;
		
		private string _NewTKod;
		
		private System.Nullable<int> _KodReg;
		
		private string _NameReg;
		
		private string _OGRN;
		
		private System.Nullable<byte> _xDelete;
		
		private System.Nullable<byte> _xImport;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKODChanging(int value);
    partial void OnKODChanged();
    partial void OnTKODChanging(string value);
    partial void OnTKODChanged();
    partial void OnNewTKodChanging(string value);
    partial void OnNewTKodChanged();
    partial void OnKodRegChanging(System.Nullable<int> value);
    partial void OnKodRegChanged();
    partial void OnNameRegChanging(string value);
    partial void OnNameRegChanged();
    partial void OnOGRNChanging(string value);
    partial void OnOGRNChanged();
    partial void OnxDeleteChanging(System.Nullable<byte> value);
    partial void OnxDeleteChanged();
    partial void OnxImportChanging(System.Nullable<byte> value);
    partial void OnxImportChanged();
    #endregion
		
		public s_StrahComp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int KOD
		{
			get
			{
				return this._KOD;
			}
			set
			{
				if ((this._KOD != value))
				{
					this.OnKODChanging(value);
					this.SendPropertyChanging();
					this._KOD = value;
					this.SendPropertyChanged("KOD");
					this.OnKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TKOD", DbType="NVarChar(255)")]
		public string TKOD
		{
			get
			{
				return this._TKOD;
			}
			set
			{
				if ((this._TKOD != value))
				{
					this.OnTKODChanging(value);
					this.SendPropertyChanging();
					this._TKOD = value;
					this.SendPropertyChanged("TKOD");
					this.OnTKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewTKod", DbType="NVarChar(100)")]
		public string NewTKod
		{
			get
			{
				return this._NewTKod;
			}
			set
			{
				if ((this._NewTKod != value))
				{
					this.OnNewTKodChanging(value);
					this.SendPropertyChanging();
					this._NewTKod = value;
					this.SendPropertyChanged("NewTKod");
					this.OnNewTKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KodReg", DbType="Int")]
		public System.Nullable<int> KodReg
		{
			get
			{
				return this._KodReg;
			}
			set
			{
				if ((this._KodReg != value))
				{
					this.OnKodRegChanging(value);
					this.SendPropertyChanging();
					this._KodReg = value;
					this.SendPropertyChanged("KodReg");
					this.OnKodRegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameReg", DbType="NVarChar(100)")]
		public string NameReg
		{
			get
			{
				return this._NameReg;
			}
			set
			{
				if ((this._NameReg != value))
				{
					this.OnNameRegChanging(value);
					this.SendPropertyChanging();
					this._NameReg = value;
					this.SendPropertyChanged("NameReg");
					this.OnNameRegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OGRN", DbType="NVarChar(13)")]
		public string OGRN
		{
			get
			{
				return this._OGRN;
			}
			set
			{
				if ((this._OGRN != value))
				{
					this.OnOGRNChanging(value);
					this.SendPropertyChanging();
					this._OGRN = value;
					this.SendPropertyChanged("OGRN");
					this.OnOGRNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xDelete", DbType="TinyInt")]
		public System.Nullable<byte> xDelete
		{
			get
			{
				return this._xDelete;
			}
			set
			{
				if ((this._xDelete != value))
				{
					this.OnxDeleteChanging(value);
					this.SendPropertyChanging();
					this._xDelete = value;
					this.SendPropertyChanged("xDelete");
					this.OnxDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xImport", DbType="TinyInt")]
		public System.Nullable<byte> xImport
		{
			get
			{
				return this._xImport;
			}
			set
			{
				if ((this._xImport != value))
				{
					this.OnxImportChanging(value);
					this.SendPropertyChanging();
					this._xImport = value;
					this.SendPropertyChanged("xImport");
					this.OnxImportChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.s_Oblast")]
	public partial class s_Oblast : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _kod;
		
		private string _NAIM;
		
		private string _NewKod;
		
		private System.Nullable<byte> _xDelete;
		
		private System.Nullable<byte> _xImport;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkodChanging(short value);
    partial void OnkodChanged();
    partial void OnNAIMChanging(string value);
    partial void OnNAIMChanged();
    partial void OnNewKodChanging(string value);
    partial void OnNewKodChanged();
    partial void OnxDeleteChanging(System.Nullable<byte> value);
    partial void OnxDeleteChanged();
    partial void OnxImportChanging(System.Nullable<byte> value);
    partial void OnxImportChanged();
    #endregion
		
		public s_Oblast()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kod", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short kod
		{
			get
			{
				return this._kod;
			}
			set
			{
				if ((this._kod != value))
				{
					this.OnkodChanging(value);
					this.SendPropertyChanging();
					this._kod = value;
					this.SendPropertyChanged("kod");
					this.OnkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAIM", DbType="NVarChar(90)")]
		public string NAIM
		{
			get
			{
				return this._NAIM;
			}
			set
			{
				if ((this._NAIM != value))
				{
					this.OnNAIMChanging(value);
					this.SendPropertyChanging();
					this._NAIM = value;
					this.SendPropertyChanged("NAIM");
					this.OnNAIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewKod", DbType="NVarChar(5)")]
		public string NewKod
		{
			get
			{
				return this._NewKod;
			}
			set
			{
				if ((this._NewKod != value))
				{
					this.OnNewKodChanging(value);
					this.SendPropertyChanging();
					this._NewKod = value;
					this.SendPropertyChanged("NewKod");
					this.OnNewKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xDelete", DbType="TinyInt")]
		public System.Nullable<byte> xDelete
		{
			get
			{
				return this._xDelete;
			}
			set
			{
				if ((this._xDelete != value))
				{
					this.OnxDeleteChanging(value);
					this.SendPropertyChanging();
					this._xDelete = value;
					this.SendPropertyChanged("xDelete");
					this.OnxDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xImport", DbType="TinyInt")]
		public System.Nullable<byte> xImport
		{
			get
			{
				return this._xImport;
			}
			set
			{
				if ((this._xImport != value))
				{
					this.OnxImportChanging(value);
					this.SendPropertyChanging();
					this._xImport = value;
					this.SendPropertyChanged("xImport");
					this.OnxImportChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StrahSpr")]
	public partial class StrahSpr : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cod;
		
		private string _TableID;
		
		private int _Number;
		
		private System.Nullable<int> _ID1;
		
		private System.Nullable<int> _ID2;
		
		private System.Nullable<int> _ID3;
		
		private System.Nullable<int> _ID4;
		
		private string _Kod1;
		
		private string _Kod2;
		
		private string _Kod3;
		
		private string _Text;
		
		private System.Nullable<System.DateTime> _DateBeg;
		
		private System.Nullable<System.DateTime> _DateEnd;
		
		private string _xInfo;
		
		private System.Nullable<byte> _xImport;
		
		private byte _xDelete;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodChanging(int value);
    partial void OnCodChanged();
    partial void OnTableIDChanging(string value);
    partial void OnTableIDChanged();
    partial void OnNumberChanging(int value);
    partial void OnNumberChanged();
    partial void OnID1Changing(System.Nullable<int> value);
    partial void OnID1Changed();
    partial void OnID2Changing(System.Nullable<int> value);
    partial void OnID2Changed();
    partial void OnID3Changing(System.Nullable<int> value);
    partial void OnID3Changed();
    partial void OnID4Changing(System.Nullable<int> value);
    partial void OnID4Changed();
    partial void OnKod1Changing(string value);
    partial void OnKod1Changed();
    partial void OnKod2Changing(string value);
    partial void OnKod2Changed();
    partial void OnKod3Changing(string value);
    partial void OnKod3Changed();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    partial void OnDateBegChanging(System.Nullable<System.DateTime> value);
    partial void OnDateBegChanged();
    partial void OnDateEndChanging(System.Nullable<System.DateTime> value);
    partial void OnDateEndChanged();
    partial void OnxInfoChanging(string value);
    partial void OnxInfoChanged();
    partial void OnxImportChanging(System.Nullable<byte> value);
    partial void OnxImportChanged();
    partial void OnxDeleteChanging(byte value);
    partial void OnxDeleteChanged();
    #endregion
		
		public StrahSpr()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Cod
		{
			get
			{
				return this._Cod;
			}
			set
			{
				if ((this._Cod != value))
				{
					this.OnCodChanging(value);
					this.SendPropertyChanging();
					this._Cod = value;
					this.SendPropertyChanged("Cod");
					this.OnCodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TableID
		{
			get
			{
				return this._TableID;
			}
			set
			{
				if ((this._TableID != value))
				{
					this.OnTableIDChanging(value);
					this.SendPropertyChanging();
					this._TableID = value;
					this.SendPropertyChanged("TableID");
					this.OnTableIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Int NOT NULL")]
		public int Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID1", DbType="Int")]
		public System.Nullable<int> ID1
		{
			get
			{
				return this._ID1;
			}
			set
			{
				if ((this._ID1 != value))
				{
					this.OnID1Changing(value);
					this.SendPropertyChanging();
					this._ID1 = value;
					this.SendPropertyChanged("ID1");
					this.OnID1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID2", DbType="Int")]
		public System.Nullable<int> ID2
		{
			get
			{
				return this._ID2;
			}
			set
			{
				if ((this._ID2 != value))
				{
					this.OnID2Changing(value);
					this.SendPropertyChanging();
					this._ID2 = value;
					this.SendPropertyChanged("ID2");
					this.OnID2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID3", DbType="Int")]
		public System.Nullable<int> ID3
		{
			get
			{
				return this._ID3;
			}
			set
			{
				if ((this._ID3 != value))
				{
					this.OnID3Changing(value);
					this.SendPropertyChanging();
					this._ID3 = value;
					this.SendPropertyChanged("ID3");
					this.OnID3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID4", DbType="Int")]
		public System.Nullable<int> ID4
		{
			get
			{
				return this._ID4;
			}
			set
			{
				if ((this._ID4 != value))
				{
					this.OnID4Changing(value);
					this.SendPropertyChanging();
					this._ID4 = value;
					this.SendPropertyChanged("ID4");
					this.OnID4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod1", DbType="NVarChar(200)")]
		public string Kod1
		{
			get
			{
				return this._Kod1;
			}
			set
			{
				if ((this._Kod1 != value))
				{
					this.OnKod1Changing(value);
					this.SendPropertyChanging();
					this._Kod1 = value;
					this.SendPropertyChanged("Kod1");
					this.OnKod1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod2", DbType="NVarChar(200)")]
		public string Kod2
		{
			get
			{
				return this._Kod2;
			}
			set
			{
				if ((this._Kod2 != value))
				{
					this.OnKod2Changing(value);
					this.SendPropertyChanging();
					this._Kod2 = value;
					this.SendPropertyChanged("Kod2");
					this.OnKod2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod3", DbType="NVarChar(200)")]
		public string Kod3
		{
			get
			{
				return this._Kod3;
			}
			set
			{
				if ((this._Kod3 != value))
				{
					this.OnKod3Changing(value);
					this.SendPropertyChanging();
					this._Kod3 = value;
					this.SendPropertyChanged("Kod3");
					this.OnKod3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(MAX)")]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateBeg", DbType="Date")]
		public System.Nullable<System.DateTime> DateBeg
		{
			get
			{
				return this._DateBeg;
			}
			set
			{
				if ((this._DateBeg != value))
				{
					this.OnDateBegChanging(value);
					this.SendPropertyChanging();
					this._DateBeg = value;
					this.SendPropertyChanged("DateBeg");
					this.OnDateBegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEnd", DbType="Date")]
		public System.Nullable<System.DateTime> DateEnd
		{
			get
			{
				return this._DateEnd;
			}
			set
			{
				if ((this._DateEnd != value))
				{
					this.OnDateEndChanging(value);
					this.SendPropertyChanging();
					this._DateEnd = value;
					this.SendPropertyChanged("DateEnd");
					this.OnDateEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xInfo", DbType="NVarChar(MAX)")]
		public string xInfo
		{
			get
			{
				return this._xInfo;
			}
			set
			{
				if ((this._xInfo != value))
				{
					this.OnxInfoChanging(value);
					this.SendPropertyChanging();
					this._xInfo = value;
					this.SendPropertyChanged("xInfo");
					this.OnxInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xImport", DbType="TinyInt")]
		public System.Nullable<byte> xImport
		{
			get
			{
				return this._xImport;
			}
			set
			{
				if ((this._xImport != value))
				{
					this.OnxImportChanging(value);
					this.SendPropertyChanging();
					this._xImport = value;
					this.SendPropertyChanged("xImport");
					this.OnxImportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xDelete", DbType="TinyInt NOT NULL")]
		public byte xDelete
		{
			get
			{
				return this._xDelete;
			}
			set
			{
				if ((this._xDelete != value))
				{
					this.OnxDeleteChanging(value);
					this.SendPropertyChanging();
					this._xDelete = value;
					this.SendPropertyChanged("xDelete");
					this.OnxDeleteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StrahReestr")]
	public partial class StrahReestr : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cod;
		
		private System.Nullable<int> _CodFile;
		
		private string _PLAT;
		
		private string _SMO_OGRN;
		
		private string _SMO_OK;
		
		private string _SMO_NAM;
		
		private System.Nullable<decimal> _LPU_1;
		
		private System.Nullable<decimal> _ORDER;
		
		private System.Nullable<int> _LPU_ST;
		
		private System.Nullable<decimal> _VIDPOM;
		
		private System.Nullable<decimal> _PODR;
		
		private System.Nullable<decimal> _PROFIL;
		
		private System.Nullable<decimal> _DET;
		
		private string _CODE_USL;
		
		private string _PRVS;
		
		private string _IDDOKT;
		
		private System.Nullable<System.DateTime> _ARR_DATE;
		
		private System.Nullable<System.DateTime> _EX_DATE;
		
		private string _DS1;
		
		private string _DS2;
		
		private string _PACIENTID;
		
		private System.Nullable<decimal> _RES_G;
		
		private System.Nullable<decimal> _ISHOD;
		
		private System.Nullable<decimal> _IDSP;
		
		private System.Nullable<decimal> _KOL_USL;
		
		private System.Nullable<decimal> _TARIF;
		
		private System.Nullable<decimal> _DoTarif;
		
		private System.Nullable<decimal> _SUM_LPU;
		
		private System.Nullable<decimal> _VPOLIS;
		
		private string _SERIA;
		
		private string _NUMBER;
		
		private string _FAMILY;
		
		private string _NAME;
		
		private string _FATHER;
		
		private System.Nullable<decimal> _POL;
		
		private System.Nullable<System.DateTime> _VOZRAST;
		
		private string _SS;
		
		private string _OS_SLUCH;
		
		private string _FAM_P;
		
		private string _IM_P;
		
		private string _OT_P;
		
		private System.Nullable<decimal> _W_P;
		
		private System.Nullable<System.DateTime> _DR_P;
		
		private string _MR;
		
		private System.Nullable<decimal> _DOCTYPE;
		
		private string _DOCSER;
		
		private string _DOCNUM;
		
		private string _OKATOG;
		
		private System.Nullable<decimal> _NOM_ZAP;
		
		private System.Nullable<decimal> _UKL;
		
		private string _NOM_USL;
		
		private System.Nullable<decimal> _ID_PAC;
		
		private System.Nullable<int> _N_ZAP;
		
		private System.Nullable<byte> _PR_NOV;
		
		private System.Nullable<int> _xUpdate;
		
		private System.Nullable<decimal> _DoSumRea;
		
		private System.Nullable<int> _DayN;
		
		private string _VID_VME;
		
		private string _VID_HMP;
		
		private string _METOD_HMP;
		
		private System.Nullable<int> _Kod_Ksg;
		
		private System.Nullable<System.DateTime> _DOCDATE;
		
		private string _DOCORG;
		
		private EntityRef<StrahFile> _StrahFile;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodChanging(int value);
    partial void OnCodChanged();
    partial void OnCodFileChanging(System.Nullable<int> value);
    partial void OnCodFileChanged();
    partial void OnPLATChanging(string value);
    partial void OnPLATChanged();
    partial void OnSMO_OGRNChanging(string value);
    partial void OnSMO_OGRNChanged();
    partial void OnSMO_OKChanging(string value);
    partial void OnSMO_OKChanged();
    partial void OnSMO_NAMChanging(string value);
    partial void OnSMO_NAMChanged();
    partial void OnLPU_1Changing(System.Nullable<decimal> value);
    partial void OnLPU_1Changed();
    partial void OnORDERChanging(System.Nullable<decimal> value);
    partial void OnORDERChanged();
    partial void OnLPU_STChanging(System.Nullable<int> value);
    partial void OnLPU_STChanged();
    partial void OnVIDPOMChanging(System.Nullable<decimal> value);
    partial void OnVIDPOMChanged();
    partial void OnPODRChanging(System.Nullable<decimal> value);
    partial void OnPODRChanged();
    partial void OnPROFILChanging(System.Nullable<decimal> value);
    partial void OnPROFILChanged();
    partial void OnDETChanging(System.Nullable<decimal> value);
    partial void OnDETChanged();
    partial void OnCODE_USLChanging(string value);
    partial void OnCODE_USLChanged();
    partial void OnPRVSChanging(string value);
    partial void OnPRVSChanged();
    partial void OnIDDOKTChanging(string value);
    partial void OnIDDOKTChanged();
    partial void OnARR_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnARR_DATEChanged();
    partial void OnEX_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEX_DATEChanged();
    partial void OnDS1Changing(string value);
    partial void OnDS1Changed();
    partial void OnDS2Changing(string value);
    partial void OnDS2Changed();
    partial void OnPACIENTIDChanging(string value);
    partial void OnPACIENTIDChanged();
    partial void OnRES_GChanging(System.Nullable<decimal> value);
    partial void OnRES_GChanged();
    partial void OnISHODChanging(System.Nullable<decimal> value);
    partial void OnISHODChanged();
    partial void OnIDSPChanging(System.Nullable<decimal> value);
    partial void OnIDSPChanged();
    partial void OnKOL_USLChanging(System.Nullable<decimal> value);
    partial void OnKOL_USLChanged();
    partial void OnTARIFChanging(System.Nullable<decimal> value);
    partial void OnTARIFChanged();
    partial void OnDoTarifChanging(System.Nullable<decimal> value);
    partial void OnDoTarifChanged();
    partial void OnSUM_LPUChanging(System.Nullable<decimal> value);
    partial void OnSUM_LPUChanged();
    partial void OnVPOLISChanging(System.Nullable<decimal> value);
    partial void OnVPOLISChanged();
    partial void OnSERIAChanging(string value);
    partial void OnSERIAChanged();
    partial void OnNUMBERChanging(string value);
    partial void OnNUMBERChanged();
    partial void OnFAMILYChanging(string value);
    partial void OnFAMILYChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnFATHERChanging(string value);
    partial void OnFATHERChanged();
    partial void OnPOLChanging(System.Nullable<decimal> value);
    partial void OnPOLChanged();
    partial void OnVOZRASTChanging(System.Nullable<System.DateTime> value);
    partial void OnVOZRASTChanged();
    partial void OnSSChanging(string value);
    partial void OnSSChanged();
    partial void OnOS_SLUCHChanging(string value);
    partial void OnOS_SLUCHChanged();
    partial void OnFAM_PChanging(string value);
    partial void OnFAM_PChanged();
    partial void OnIM_PChanging(string value);
    partial void OnIM_PChanged();
    partial void OnOT_PChanging(string value);
    partial void OnOT_PChanged();
    partial void OnW_PChanging(System.Nullable<decimal> value);
    partial void OnW_PChanged();
    partial void OnDR_PChanging(System.Nullable<System.DateTime> value);
    partial void OnDR_PChanged();
    partial void OnMRChanging(string value);
    partial void OnMRChanged();
    partial void OnDOCTYPEChanging(System.Nullable<decimal> value);
    partial void OnDOCTYPEChanged();
    partial void OnDOCSERChanging(string value);
    partial void OnDOCSERChanged();
    partial void OnDOCNUMChanging(string value);
    partial void OnDOCNUMChanged();
    partial void OnOKATOGChanging(string value);
    partial void OnOKATOGChanged();
    partial void OnNOM_ZAPChanging(System.Nullable<decimal> value);
    partial void OnNOM_ZAPChanged();
    partial void OnUKLChanging(System.Nullable<decimal> value);
    partial void OnUKLChanged();
    partial void OnNOM_USLChanging(string value);
    partial void OnNOM_USLChanged();
    partial void OnID_PACChanging(System.Nullable<decimal> value);
    partial void OnID_PACChanged();
    partial void OnN_ZAPChanging(System.Nullable<int> value);
    partial void OnN_ZAPChanged();
    partial void OnPR_NOVChanging(System.Nullable<byte> value);
    partial void OnPR_NOVChanged();
    partial void OnxUpdateChanging(System.Nullable<int> value);
    partial void OnxUpdateChanged();
    partial void OnDoSumReaChanging(System.Nullable<decimal> value);
    partial void OnDoSumReaChanged();
    partial void OnDayNChanging(System.Nullable<int> value);
    partial void OnDayNChanged();
    partial void OnVID_VMEChanging(string value);
    partial void OnVID_VMEChanged();
    partial void OnVID_HMPChanging(string value);
    partial void OnVID_HMPChanged();
    partial void OnMETOD_HMPChanging(string value);
    partial void OnMETOD_HMPChanged();
    partial void OnKod_KsgChanging(System.Nullable<int> value);
    partial void OnKod_KsgChanged();
    partial void OnDOCDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDOCDATEChanged();
    partial void OnDOCORGChanging(string value);
    partial void OnDOCORGChanged();
    #endregion
		
		public StrahReestr()
		{
			this._StrahFile = default(EntityRef<StrahFile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Cod
		{
			get
			{
				return this._Cod;
			}
			set
			{
				if ((this._Cod != value))
				{
					this.OnCodChanging(value);
					this.SendPropertyChanging();
					this._Cod = value;
					this.SendPropertyChanged("Cod");
					this.OnCodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodFile", DbType="Int")]
		public System.Nullable<int> CodFile
		{
			get
			{
				return this._CodFile;
			}
			set
			{
				if ((this._CodFile != value))
				{
					if (this._StrahFile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodFileChanging(value);
					this.SendPropertyChanging();
					this._CodFile = value;
					this.SendPropertyChanged("CodFile");
					this.OnCodFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAT", DbType="NVarChar(5)")]
		public string PLAT
		{
			get
			{
				return this._PLAT;
			}
			set
			{
				if ((this._PLAT != value))
				{
					this.OnPLATChanging(value);
					this.SendPropertyChanging();
					this._PLAT = value;
					this.SendPropertyChanged("PLAT");
					this.OnPLATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMO_OGRN", DbType="NVarChar(15)")]
		public string SMO_OGRN
		{
			get
			{
				return this._SMO_OGRN;
			}
			set
			{
				if ((this._SMO_OGRN != value))
				{
					this.OnSMO_OGRNChanging(value);
					this.SendPropertyChanging();
					this._SMO_OGRN = value;
					this.SendPropertyChanged("SMO_OGRN");
					this.OnSMO_OGRNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMO_OK", DbType="NVarChar(5)")]
		public string SMO_OK
		{
			get
			{
				return this._SMO_OK;
			}
			set
			{
				if ((this._SMO_OK != value))
				{
					this.OnSMO_OKChanging(value);
					this.SendPropertyChanging();
					this._SMO_OK = value;
					this.SendPropertyChanged("SMO_OK");
					this.OnSMO_OKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMO_NAM", DbType="NVarChar(100)")]
		public string SMO_NAM
		{
			get
			{
				return this._SMO_NAM;
			}
			set
			{
				if ((this._SMO_NAM != value))
				{
					this.OnSMO_NAMChanging(value);
					this.SendPropertyChanging();
					this._SMO_NAM = value;
					this.SendPropertyChanged("SMO_NAM");
					this.OnSMO_NAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LPU_1", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> LPU_1
		{
			get
			{
				return this._LPU_1;
			}
			set
			{
				if ((this._LPU_1 != value))
				{
					this.OnLPU_1Changing(value);
					this.SendPropertyChanging();
					this._LPU_1 = value;
					this.SendPropertyChanged("LPU_1");
					this.OnLPU_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this.OnORDERChanging(value);
					this.SendPropertyChanging();
					this._ORDER = value;
					this.SendPropertyChanged("ORDER");
					this.OnORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LPU_ST", DbType="Int")]
		public System.Nullable<int> LPU_ST
		{
			get
			{
				return this._LPU_ST;
			}
			set
			{
				if ((this._LPU_ST != value))
				{
					this.OnLPU_STChanging(value);
					this.SendPropertyChanging();
					this._LPU_ST = value;
					this.SendPropertyChanged("LPU_ST");
					this.OnLPU_STChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIDPOM", DbType="Decimal(4,0)")]
		public System.Nullable<decimal> VIDPOM
		{
			get
			{
				return this._VIDPOM;
			}
			set
			{
				if ((this._VIDPOM != value))
				{
					this.OnVIDPOMChanging(value);
					this.SendPropertyChanging();
					this._VIDPOM = value;
					this.SendPropertyChanged("VIDPOM");
					this.OnVIDPOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PODR", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> PODR
		{
			get
			{
				return this._PODR;
			}
			set
			{
				if ((this._PODR != value))
				{
					this.OnPODRChanging(value);
					this.SendPropertyChanging();
					this._PODR = value;
					this.SendPropertyChanged("PODR");
					this.OnPODRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROFIL", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> PROFIL
		{
			get
			{
				return this._PROFIL;
			}
			set
			{
				if ((this._PROFIL != value))
				{
					this.OnPROFILChanging(value);
					this.SendPropertyChanging();
					this._PROFIL = value;
					this.SendPropertyChanged("PROFIL");
					this.OnPROFILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DET", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> DET
		{
			get
			{
				return this._DET;
			}
			set
			{
				if ((this._DET != value))
				{
					this.OnDETChanging(value);
					this.SendPropertyChanging();
					this._DET = value;
					this.SendPropertyChanged("DET");
					this.OnDETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE_USL", DbType="NVarChar(20)")]
		public string CODE_USL
		{
			get
			{
				return this._CODE_USL;
			}
			set
			{
				if ((this._CODE_USL != value))
				{
					this.OnCODE_USLChanging(value);
					this.SendPropertyChanging();
					this._CODE_USL = value;
					this.SendPropertyChanged("CODE_USL");
					this.OnCODE_USLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRVS", DbType="NVarChar(9)")]
		public string PRVS
		{
			get
			{
				return this._PRVS;
			}
			set
			{
				if ((this._PRVS != value))
				{
					this.OnPRVSChanging(value);
					this.SendPropertyChanging();
					this._PRVS = value;
					this.SendPropertyChanged("PRVS");
					this.OnPRVSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDOKT", DbType="NVarChar(16)")]
		public string IDDOKT
		{
			get
			{
				return this._IDDOKT;
			}
			set
			{
				if ((this._IDDOKT != value))
				{
					this.OnIDDOKTChanging(value);
					this.SendPropertyChanging();
					this._IDDOKT = value;
					this.SendPropertyChanged("IDDOKT");
					this.OnIDDOKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARR_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> ARR_DATE
		{
			get
			{
				return this._ARR_DATE;
			}
			set
			{
				if ((this._ARR_DATE != value))
				{
					this.OnARR_DATEChanging(value);
					this.SendPropertyChanging();
					this._ARR_DATE = value;
					this.SendPropertyChanged("ARR_DATE");
					this.OnARR_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EX_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> EX_DATE
		{
			get
			{
				return this._EX_DATE;
			}
			set
			{
				if ((this._EX_DATE != value))
				{
					this.OnEX_DATEChanging(value);
					this.SendPropertyChanging();
					this._EX_DATE = value;
					this.SendPropertyChanged("EX_DATE");
					this.OnEX_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS1", DbType="NVarChar(10)")]
		public string DS1
		{
			get
			{
				return this._DS1;
			}
			set
			{
				if ((this._DS1 != value))
				{
					this.OnDS1Changing(value);
					this.SendPropertyChanging();
					this._DS1 = value;
					this.SendPropertyChanged("DS1");
					this.OnDS1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS2", DbType="NVarChar(10)")]
		public string DS2
		{
			get
			{
				return this._DS2;
			}
			set
			{
				if ((this._DS2 != value))
				{
					this.OnDS2Changing(value);
					this.SendPropertyChanging();
					this._DS2 = value;
					this.SendPropertyChanged("DS2");
					this.OnDS2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACIENTID", DbType="NVarChar(50)")]
		public string PACIENTID
		{
			get
			{
				return this._PACIENTID;
			}
			set
			{
				if ((this._PACIENTID != value))
				{
					this.OnPACIENTIDChanging(value);
					this.SendPropertyChanging();
					this._PACIENTID = value;
					this.SendPropertyChanged("PACIENTID");
					this.OnPACIENTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RES_G", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> RES_G
		{
			get
			{
				return this._RES_G;
			}
			set
			{
				if ((this._RES_G != value))
				{
					this.OnRES_GChanging(value);
					this.SendPropertyChanging();
					this._RES_G = value;
					this.SendPropertyChanged("RES_G");
					this.OnRES_GChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISHOD", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> ISHOD
		{
			get
			{
				return this._ISHOD;
			}
			set
			{
				if ((this._ISHOD != value))
				{
					this.OnISHODChanging(value);
					this.SendPropertyChanging();
					this._ISHOD = value;
					this.SendPropertyChanged("ISHOD");
					this.OnISHODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSP", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> IDSP
		{
			get
			{
				return this._IDSP;
			}
			set
			{
				if ((this._IDSP != value))
				{
					this.OnIDSPChanging(value);
					this.SendPropertyChanging();
					this._IDSP = value;
					this.SendPropertyChanged("IDSP");
					this.OnIDSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOL_USL", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> KOL_USL
		{
			get
			{
				return this._KOL_USL;
			}
			set
			{
				if ((this._KOL_USL != value))
				{
					this.OnKOL_USLChanging(value);
					this.SendPropertyChanging();
					this._KOL_USL = value;
					this.SendPropertyChanged("KOL_USL");
					this.OnKOL_USLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIF", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> TARIF
		{
			get
			{
				return this._TARIF;
			}
			set
			{
				if ((this._TARIF != value))
				{
					this.OnTARIFChanging(value);
					this.SendPropertyChanging();
					this._TARIF = value;
					this.SendPropertyChanged("TARIF");
					this.OnTARIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoTarif", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> DoTarif
		{
			get
			{
				return this._DoTarif;
			}
			set
			{
				if ((this._DoTarif != value))
				{
					this.OnDoTarifChanging(value);
					this.SendPropertyChanging();
					this._DoTarif = value;
					this.SendPropertyChanged("DoTarif");
					this.OnDoTarifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUM_LPU", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> SUM_LPU
		{
			get
			{
				return this._SUM_LPU;
			}
			set
			{
				if ((this._SUM_LPU != value))
				{
					this.OnSUM_LPUChanging(value);
					this.SendPropertyChanging();
					this._SUM_LPU = value;
					this.SendPropertyChanged("SUM_LPU");
					this.OnSUM_LPUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VPOLIS", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> VPOLIS
		{
			get
			{
				return this._VPOLIS;
			}
			set
			{
				if ((this._VPOLIS != value))
				{
					this.OnVPOLISChanging(value);
					this.SendPropertyChanging();
					this._VPOLIS = value;
					this.SendPropertyChanged("VPOLIS");
					this.OnVPOLISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIA", DbType="NVarChar(10)")]
		public string SERIA
		{
			get
			{
				return this._SERIA;
			}
			set
			{
				if ((this._SERIA != value))
				{
					this.OnSERIAChanging(value);
					this.SendPropertyChanging();
					this._SERIA = value;
					this.SendPropertyChanged("SERIA");
					this.OnSERIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMBER", DbType="NVarChar(20)")]
		public string NUMBER
		{
			get
			{
				return this._NUMBER;
			}
			set
			{
				if ((this._NUMBER != value))
				{
					this.OnNUMBERChanging(value);
					this.SendPropertyChanging();
					this._NUMBER = value;
					this.SendPropertyChanged("NUMBER");
					this.OnNUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAMILY", DbType="NVarChar(40)")]
		public string FAMILY
		{
			get
			{
				return this._FAMILY;
			}
			set
			{
				if ((this._FAMILY != value))
				{
					this.OnFAMILYChanging(value);
					this.SendPropertyChanging();
					this._FAMILY = value;
					this.SendPropertyChanged("FAMILY");
					this.OnFAMILYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(40)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATHER", DbType="NVarChar(40)")]
		public string FATHER
		{
			get
			{
				return this._FATHER;
			}
			set
			{
				if ((this._FATHER != value))
				{
					this.OnFATHERChanging(value);
					this.SendPropertyChanging();
					this._FATHER = value;
					this.SendPropertyChanged("FATHER");
					this.OnFATHERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POL", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> POL
		{
			get
			{
				return this._POL;
			}
			set
			{
				if ((this._POL != value))
				{
					this.OnPOLChanging(value);
					this.SendPropertyChanging();
					this._POL = value;
					this.SendPropertyChanged("POL");
					this.OnPOLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VOZRAST", DbType="Date")]
		public System.Nullable<System.DateTime> VOZRAST
		{
			get
			{
				return this._VOZRAST;
			}
			set
			{
				if ((this._VOZRAST != value))
				{
					this.OnVOZRASTChanging(value);
					this.SendPropertyChanging();
					this._VOZRAST = value;
					this.SendPropertyChanged("VOZRAST");
					this.OnVOZRASTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SS", DbType="NVarChar(14)")]
		public string SS
		{
			get
			{
				return this._SS;
			}
			set
			{
				if ((this._SS != value))
				{
					this.OnSSChanging(value);
					this.SendPropertyChanging();
					this._SS = value;
					this.SendPropertyChanged("SS");
					this.OnSSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OS_SLUCH", DbType="NVarChar(2)")]
		public string OS_SLUCH
		{
			get
			{
				return this._OS_SLUCH;
			}
			set
			{
				if ((this._OS_SLUCH != value))
				{
					this.OnOS_SLUCHChanging(value);
					this.SendPropertyChanging();
					this._OS_SLUCH = value;
					this.SendPropertyChanged("OS_SLUCH");
					this.OnOS_SLUCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAM_P", DbType="NVarChar(40)")]
		public string FAM_P
		{
			get
			{
				return this._FAM_P;
			}
			set
			{
				if ((this._FAM_P != value))
				{
					this.OnFAM_PChanging(value);
					this.SendPropertyChanging();
					this._FAM_P = value;
					this.SendPropertyChanged("FAM_P");
					this.OnFAM_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IM_P", DbType="NVarChar(40)")]
		public string IM_P
		{
			get
			{
				return this._IM_P;
			}
			set
			{
				if ((this._IM_P != value))
				{
					this.OnIM_PChanging(value);
					this.SendPropertyChanging();
					this._IM_P = value;
					this.SendPropertyChanged("IM_P");
					this.OnIM_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OT_P", DbType="NVarChar(40)")]
		public string OT_P
		{
			get
			{
				return this._OT_P;
			}
			set
			{
				if ((this._OT_P != value))
				{
					this.OnOT_PChanging(value);
					this.SendPropertyChanging();
					this._OT_P = value;
					this.SendPropertyChanged("OT_P");
					this.OnOT_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_W_P", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> W_P
		{
			get
			{
				return this._W_P;
			}
			set
			{
				if ((this._W_P != value))
				{
					this.OnW_PChanging(value);
					this.SendPropertyChanging();
					this._W_P = value;
					this.SendPropertyChanged("W_P");
					this.OnW_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DR_P", DbType="Date")]
		public System.Nullable<System.DateTime> DR_P
		{
			get
			{
				return this._DR_P;
			}
			set
			{
				if ((this._DR_P != value))
				{
					this.OnDR_PChanging(value);
					this.SendPropertyChanging();
					this._DR_P = value;
					this.SendPropertyChanged("DR_P");
					this.OnDR_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MR", DbType="NVarChar(100)")]
		public string MR
		{
			get
			{
				return this._MR;
			}
			set
			{
				if ((this._MR != value))
				{
					this.OnMRChanging(value);
					this.SendPropertyChanging();
					this._MR = value;
					this.SendPropertyChanged("MR");
					this.OnMRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCTYPE", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> DOCTYPE
		{
			get
			{
				return this._DOCTYPE;
			}
			set
			{
				if ((this._DOCTYPE != value))
				{
					this.OnDOCTYPEChanging(value);
					this.SendPropertyChanging();
					this._DOCTYPE = value;
					this.SendPropertyChanged("DOCTYPE");
					this.OnDOCTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCSER", DbType="NVarChar(10)")]
		public string DOCSER
		{
			get
			{
				return this._DOCSER;
			}
			set
			{
				if ((this._DOCSER != value))
				{
					this.OnDOCSERChanging(value);
					this.SendPropertyChanging();
					this._DOCSER = value;
					this.SendPropertyChanged("DOCSER");
					this.OnDOCSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNUM", DbType="NVarChar(20)")]
		public string DOCNUM
		{
			get
			{
				return this._DOCNUM;
			}
			set
			{
				if ((this._DOCNUM != value))
				{
					this.OnDOCNUMChanging(value);
					this.SendPropertyChanging();
					this._DOCNUM = value;
					this.SendPropertyChanged("DOCNUM");
					this.OnDOCNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OKATOG", DbType="NVarChar(11)")]
		public string OKATOG
		{
			get
			{
				return this._OKATOG;
			}
			set
			{
				if ((this._OKATOG != value))
				{
					this.OnOKATOGChanging(value);
					this.SendPropertyChanging();
					this._OKATOG = value;
					this.SendPropertyChanged("OKATOG");
					this.OnOKATOGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_ZAP", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> NOM_ZAP
		{
			get
			{
				return this._NOM_ZAP;
			}
			set
			{
				if ((this._NOM_ZAP != value))
				{
					this.OnNOM_ZAPChanging(value);
					this.SendPropertyChanging();
					this._NOM_ZAP = value;
					this.SendPropertyChanged("NOM_ZAP");
					this.OnNOM_ZAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UKL", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> UKL
		{
			get
			{
				return this._UKL;
			}
			set
			{
				if ((this._UKL != value))
				{
					this.OnUKLChanging(value);
					this.SendPropertyChanging();
					this._UKL = value;
					this.SendPropertyChanged("UKL");
					this.OnUKLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_USL", DbType="NVarChar(MAX)")]
		public string NOM_USL
		{
			get
			{
				return this._NOM_USL;
			}
			set
			{
				if ((this._NOM_USL != value))
				{
					this.OnNOM_USLChanging(value);
					this.SendPropertyChanging();
					this._NOM_USL = value;
					this.SendPropertyChanged("NOM_USL");
					this.OnNOM_USLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PAC", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID_PAC
		{
			get
			{
				return this._ID_PAC;
			}
			set
			{
				if ((this._ID_PAC != value))
				{
					this.OnID_PACChanging(value);
					this.SendPropertyChanging();
					this._ID_PAC = value;
					this.SendPropertyChanged("ID_PAC");
					this.OnID_PACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_ZAP", DbType="Int")]
		public System.Nullable<int> N_ZAP
		{
			get
			{
				return this._N_ZAP;
			}
			set
			{
				if ((this._N_ZAP != value))
				{
					this.OnN_ZAPChanging(value);
					this.SendPropertyChanging();
					this._N_ZAP = value;
					this.SendPropertyChanged("N_ZAP");
					this.OnN_ZAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_NOV", DbType="TinyInt")]
		public System.Nullable<byte> PR_NOV
		{
			get
			{
				return this._PR_NOV;
			}
			set
			{
				if ((this._PR_NOV != value))
				{
					this.OnPR_NOVChanging(value);
					this.SendPropertyChanging();
					this._PR_NOV = value;
					this.SendPropertyChanged("PR_NOV");
					this.OnPR_NOVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xUpdate", DbType="Int")]
		public System.Nullable<int> xUpdate
		{
			get
			{
				return this._xUpdate;
			}
			set
			{
				if ((this._xUpdate != value))
				{
					this.OnxUpdateChanging(value);
					this.SendPropertyChanging();
					this._xUpdate = value;
					this.SendPropertyChanged("xUpdate");
					this.OnxUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoSumRea", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> DoSumRea
		{
			get
			{
				return this._DoSumRea;
			}
			set
			{
				if ((this._DoSumRea != value))
				{
					this.OnDoSumReaChanging(value);
					this.SendPropertyChanging();
					this._DoSumRea = value;
					this.SendPropertyChanged("DoSumRea");
					this.OnDoSumReaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayN", DbType="Int")]
		public System.Nullable<int> DayN
		{
			get
			{
				return this._DayN;
			}
			set
			{
				if ((this._DayN != value))
				{
					this.OnDayNChanging(value);
					this.SendPropertyChanging();
					this._DayN = value;
					this.SendPropertyChanged("DayN");
					this.OnDayNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VID_VME", DbType="NVarChar(15)")]
		public string VID_VME
		{
			get
			{
				return this._VID_VME;
			}
			set
			{
				if ((this._VID_VME != value))
				{
					this.OnVID_VMEChanging(value);
					this.SendPropertyChanging();
					this._VID_VME = value;
					this.SendPropertyChanged("VID_VME");
					this.OnVID_VMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VID_HMP", DbType="NVarChar(12)")]
		public string VID_HMP
		{
			get
			{
				return this._VID_HMP;
			}
			set
			{
				if ((this._VID_HMP != value))
				{
					this.OnVID_HMPChanging(value);
					this.SendPropertyChanging();
					this._VID_HMP = value;
					this.SendPropertyChanged("VID_HMP");
					this.OnVID_HMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_METOD_HMP", DbType="NVarChar(5)")]
		public string METOD_HMP
		{
			get
			{
				return this._METOD_HMP;
			}
			set
			{
				if ((this._METOD_HMP != value))
				{
					this.OnMETOD_HMPChanging(value);
					this.SendPropertyChanging();
					this._METOD_HMP = value;
					this.SendPropertyChanged("METOD_HMP");
					this.OnMETOD_HMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod_Ksg", DbType="Int")]
		public System.Nullable<int> Kod_Ksg
		{
			get
			{
				return this._Kod_Ksg;
			}
			set
			{
				if ((this._Kod_Ksg != value))
				{
					this.OnKod_KsgChanging(value);
					this.SendPropertyChanging();
					this._Kod_Ksg = value;
					this.SendPropertyChanged("Kod_Ksg");
					this.OnKod_KsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="Date")]
		public System.Nullable<System.DateTime> DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this.OnDOCDATEChanging(value);
					this.SendPropertyChanging();
					this._DOCDATE = value;
					this.SendPropertyChanged("DOCDATE");
					this.OnDOCDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCORG", DbType="NVarChar(1000)")]
		public string DOCORG
		{
			get
			{
				return this._DOCORG;
			}
			set
			{
				if ((this._DOCORG != value))
				{
					this.OnDOCORGChanging(value);
					this.SendPropertyChanging();
					this._DOCORG = value;
					this.SendPropertyChanged("DOCORG");
					this.OnDOCORGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StrahFile_StrahReestr", Storage="_StrahFile", ThisKey="CodFile", OtherKey="Cod", IsForeignKey=true, DeleteRule="CASCADE")]
		public StrahFile StrahFile
		{
			get
			{
				return this._StrahFile.Entity;
			}
			set
			{
				StrahFile previousValue = this._StrahFile.Entity;
				if (((previousValue != value) 
							|| (this._StrahFile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StrahFile.Entity = null;
						previousValue.StrahReestr.Remove(this);
					}
					this._StrahFile.Entity = value;
					if ((value != null))
					{
						value.StrahReestr.Add(this);
						this._CodFile = value.Cod;
					}
					else
					{
						this._CodFile = default(Nullable<int>);
					}
					this.SendPropertyChanged("StrahFile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
